import React from "react";
import { Shield, Lock, Info, X } from "lucide-react";

interface LegalModalProps {
  type: "tos" | "privacy";
  onClose: () => void;
}

export default function LegalModal({ type, onClose }: LegalModalProps) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="bg-[#0A0A0A] border border-white/10 rounded-2xl max-w-2xl w-full max-h-[80vh] flex flex-col shadow-[0_0_50px_rgba(255,95,21,0.15)] overflow-hidden font-sans">
        
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-white/10 bg-zinc-950/40">
          <div className="flex items-center space-x-2.5">
            {type === "tos" ? (
              <>
                <Shield className="w-5 h-5 text-[#FF5F15]" />
                <h2 className="text-lg font-black text-white uppercase tracking-wider font-mono">Terms of Service</h2>
              </>
            ) : (
              <>
                <Lock className="w-5 h-5 text-[#FF5F15]" />
                <h2 className="text-lg font-black text-white uppercase tracking-wider font-mono">Privacy Policy</h2>
              </>
            )}
          </div>
          <button 
            onClick={onClose}
            className="p-1 hover:bg-white/5 rounded-lg text-zinc-400 hover:text-white transition-colors cursor-pointer"
            aria-label="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto space-y-5 text-sm text-zinc-450 leading-relaxed font-sans">
          
          <div className="p-4 bg-zinc-950 border border-white/5 rounded-xl flex items-start space-x-3">
            <Info className="w-5 h-5 text-[#FF5F15] shrink-0 mt-0.5" />
            <p className="text-xs text-zinc-400 font-mono">
              TACTICAL STATUS: OPERATIONAL COMPLIANCE MVP VERIFICATION BASELINE. ALL METRICS RESIDE WITHIN USER TELEMETRY SYSTEM LOCAL STORAGE CACHE.
            </p>
          </div>

          {type === "tos" ? (
            <>
              <section className="space-y-2">
                <h3 className="text-white font-extrabold uppercase font-mono text-xs">1. Scope of Guidance</h3>
                <p>
                  RADICAL is a health tracking and motivational tool designed to support personal wellness goals. The workouts, diet structures, and habit suggestions generated by the system are for general educational purposes only.
                </p>
              </section>

              <section className="space-y-2">
                <h3 className="text-white font-extrabold uppercase font-mono text-xs text-[#FF5F15]">2. MEDICAL DISCLAIMER & SAFETY NOTICE</h3>
                <p className="font-bold text-zinc-300">
                  RADICAL does not provide medical advice. We are not doctors, nutritionists, or certified athletic therapists. Exercise, diet adjustments, and habit changes can carry physiological risks.
                </p>
                <p>
                  You must consult with a qualified health professional before initiating any workout regimes (including Zone 2 or metabolic conditioning), diet plans (such as Keto or Carnivore), or vice-elimination protocols. If you experience dizziness, pain, or shortness of breath, stop immediately and seek medical attention.
                </p>
              </section>

              <section className="space-y-2">
                <h3 className="text-white font-extrabold uppercase font-mono text-xs">3. Local Data Model</h3>
                <p>
                  RADICAL runs entirely client-side. Your biometric data, workout schedules, steps logs, and checklists are preserved strictly in your local browser storage cache (localStorage). We bear no responsibility for data loss resulting from browser cache clearings, device shifts, or local storage failures.
                </p>
              </section>

              <section className="space-y-2">
                <h3 className="text-white font-extrabold uppercase font-mono text-xs">4. AI Coaching Limitation</h3>
                <p>
                  The integrated AI Coach and Analyzer are powered by Google Gemini API endpoints. AI outputs can be inaccurate, simulated, or speculative. Treat coach text as conceptual guidelines, never as medical directives or absolute facts.
                </p>
              </section>
            </>
          ) : (
            <>
              <section className="space-y-2">
                <h3 className="text-white font-extrabold uppercase font-mono text-xs">1. Data Minimization Baseline</h3>
                <p>
                  Privacy is central to the RADICAL philosophy. The app is engineered to be stateless from a server perspective. We do not maintain any user database, credentials store, or telemetry repository on our servers.
                </p>
              </section>

              <section className="space-y-2">
                <h3 className="text-white font-extrabold uppercase font-mono text-xs">2. Storage Architecture</h3>
                <p>
                  All metrics—including your name, biometrics, logs, goals, and chat transcripts—are stored directly on your physical device using your web browser's <code>localStorage</code> mechanism. This data never leaves your device unless sent to Gemini API endpoints for custom plan generation or performance analysis.
                </p>
              </section>

              <section className="space-y-2">
                <h3 className="text-white font-extrabold uppercase font-mono text-xs">3. Third-Party API Telemetry</h3>
                <p>
                  To provide personalized plan generation, performance analytics, and chat, the parameters you input are processed through Google Gemini API. This data is subject to Google's API Privacy Terms and is not stored or shared for advertising purposes. No credit card details, passwords, or persistent identifiers are transmitted.
                </p>
              </section>

              <section className="space-y-2">
                <h3 className="text-white font-extrabold uppercase font-mono text-xs">4. Changes and Control</h3>
                <p>
                  You retain absolute control over your data. To wipe all stored data from RADICAL instantly, navigate to the Dashboard settings and trigger the "Wipe All Cache Metrics" protocol. Clearing your browser's site cache also deletes this data permanently.
                </p>
              </section>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-white/10 bg-zinc-950/40 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2.5 bg-zinc-900 border border-white/10 hover:border-white/20 text-xs font-mono font-bold uppercase rounded-lg text-zinc-300 hover:text-white transition-colors cursor-pointer"
          >
            Acknowledge
          </button>
        </div>

      </div>
    </div>
  );
}
